apiVersion: apps/v1
kind: Deployment
metadata:
  name: jllovet-udacitydevops
  labels:
    app: jllovet-udacitydevops
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jllovet-udacitydevops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jllovet-udacitydevops
    spec:
      containers:
      - image: jllovet/udacitydevops
        imagePullPolicy: Always
        name: udacitydevops
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: jllovet-udacitydevops-service
spec:
  selector:
    app: jllovet-udacitydevops
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30000
